# Generated by Django 5.0 on 2024-01-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0024_contact_alter_question_question_image_and_more'),
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interviewer.question')),
            ],
        ),
    ]
