runtime: python311
entrypoint: gunicorn -b :$PORT djangoProject.wsgi

beta_settings:
  cloud_sql_instances: interviewer-instance

runtime_config:
  python_version: 3

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 10  # Adjust this value as needed, but stay within the limit

#instance_class: F1
#automatic_scaling:
#  min_instances: 0
#  max_instances: 2
#  target_cpu_utilization: 0.8
#  min_pending_latency: automatic
#  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto


env_variables:
  APPENGINE_URL: https://interviewer-project.uc.r.appspot.com