# Generated by Django 4.2.7 on 2023-11-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0002_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
