# Generated by Django 4.2.7 on 2023-11-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0007_alter_question_description_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interviewer.category'),
        ),
    ]
