# Generated by Django 4.2.7 on 2023-11-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0009_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
