# Generated by Django 4.2.7 on 2023-11-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0012_category_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='dropdown',
        ),
    ]
