# Generated by Django 4.2.7 on 2023-11-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0013_remove_category_dropdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
