# Generated by Django 4.2.7 on 2023-11-28 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0014_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
