# Generated by Django 4.2.7 on 2023-11-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0017_alter_question_is_active_alter_question_is_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='questions/1.jpg', upload_to='questions/'),
        ),
    ]
