# Generated by Django 4.2.7 on 2023-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0018_alter_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('test_detail_name', models.CharField(max_length=200, null=True)),
                ('department_name', models.CharField(max_length=200, null=True)),
                ('test_description', models.CharField(blank=True, max_length=200, null=True)),
                ('question_description', models.TextField()),
                ('answer_one', models.CharField(max_length=200, null=True)),
                ('answer_two', models.CharField(max_length=200, null=True)),
                ('answer_three', models.CharField(max_length=200, null=True)),
                ('answer_four', models.CharField(max_length=200, null=True)),
                ('answer_five', models.CharField(max_length=200, null=True)),
                ('question_image', models.ImageField(blank=True, upload_to='test/')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
    ]
