# Generated by Django 4.2.7 on 2023-12-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0019_testdetail_remove_question_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdetail',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interviewer.question'),
        ),
    ]
