# Generated by Django 4.2.7 on 2023-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0022_remove_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('test_detail_name', models.CharField(max_length=200, null=True)),
                ('department_name', models.CharField(max_length=200, null=True)),
                ('test_description', models.CharField(blank=True, max_length=200, null=True)),
                ('question_description', models.TextField(null=True)),
                ('answer_one', models.CharField(max_length=200, null=True)),
                ('answer_two', models.CharField(max_length=200, null=True)),
                ('answer_three', models.CharField(max_length=200, null=True)),
                ('answer_four', models.CharField(max_length=200, null=True)),
                ('answer_five', models.CharField(max_length=200, null=True)),
                ('question_image', models.ImageField(blank=True, upload_to='test/')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_questions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='test/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='test_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='department_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='TestDetail',
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ManyToManyField(to='interviewer.test'),
        ),
    ]
