# Generated by Django 5.0 on 2024-01-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0023_test_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='test/'),
        ),
    ]
